# -*- coding: utf-8 -*-
"""ILPD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pYqTItVSm_EwRNJWY4rujt2QjRc167VB
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

a=pd.read_csv("/content/Indian Liver Patient Dataset (ILPD).csv")

a.head()

a.replace({"Female":1,"Male":2},inplace=True)
a.head()

a['is_patient'].replace({1:0,2:1},inplace=True)

a.tail()

a.head()

a.isnull().sum()

a.dropna(axis=0,inplace=True)

a.isnull().sum()

X=a.drop(columns="is_patient",axis=1)
Y=a['is_patient']

q,w,e,r=train_test_split(X,Y,test_size=0.2,random_state=2)

model=LogisticRegression()

model.fit(q,e)

s=model.predict(q)
d=accuracy_score(s,e)
print(d)

s=model.predict(w)
d=accuracy_score(s,r)
print(d)

a.info()

a.describe()

