# -*- coding: utf-8 -*-
"""svm_diabatic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VU7jOgfdTHscS0Byj6CItcauan4lDo6i
"""

import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

a=pd.read_csv("/content/A.csv")

a.head()

a.shape

a['Outcome'].value_counts()

s=a.drop(columns='Outcome',axis=1)
d=a['Outcome']

q,w,e,r=train_test_split(s,d,test_size=0.2,random_state=2)

model=svm.SVC()

model.fit(q,e)

z=model.predict(q)
x=accuracy_score(z,e)

print(x)

c=model.predict(w)
v=accuracy_score(c,r)
print(v)

w.iloc[21]

r.iloc[21]

t=(0,145,0,0,0,44,0,31)
y=np.asarray(t)
u=y.reshape(1,-1)
i=model.predict(u)
print(i)
if(i==0):
  print("it is diabatics")
else:
  print("it is not diabatics")

import pickle

filename='trained_model.sav'
pickle.dump(model,open(filename,'wb'))

m=pickle.load(open('/content/trained_model.sav','rb'))

t=(0,145,0,0,0,44,0,31)
y=np.asarray(t)
u=y.reshape(1,-1)
i=model.predict(u)
print(i)
if(i==1):
  print("it is diabatics")
else:
  print("it is not diabatics")
  


